version: '3.6'

services:

  postgres:
    image: postgres
    volumes:
      - ./db_data:/var/lib/postgresql/data
      - ./demo-medium.sql:/docker-entrypoint-initdb.d/demo-medium.sql
    container_name: ${COMPOSE_PROJECT_NAME}
    restart: unless-stopped
    ports:
      - "54321:5432"
    environment:
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"

volumes:
  postgres:
